name: mijn_iptv_app
description: VibePlay+ IPTV
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸŒ Netwerk & opslag
  http: ^1.2.2
  shared_preferences: ^2.3.2

  # ðŸŽ¥ Videoplayer
  video_player: ^2.9.1

  # ðŸ“º Chromecast (alleen actief buiten web)
  cast: ^2.1.0

  # âš™ï¸ Stabiliteit
  video_player_platform_interface: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos.json
    - assets/logos/
